### ISSUE TITLE
installing the plugin - v1.0.0 - beta0003 on a v 6.0.0 - beta 0004 throws an exception

### ISSUE THREAD

**Issue by seanfarmar** [Particular/ServiceControl.Plugin.Nsb6.CustomChecks#16]
Reported by customer
https://nservicebus.desk.com/agent/case/18550

```Method not found: 'System.Collections.Generic.IList`1<System.Type> NServiceBus.SettingsExtentions.GetAvailableTypes(NServiceBus.Settings.ReadOnlySettings)'.

at ServiceControl.Plugin.CustomChecks.CustomChecks.Setup(FeatureConfigurationContext context)
   at NServiceBus.Features.FeatureActivator.ActivateFeature(FeatureInfo featureInfo, List`1 featuresToActivate, IConfigureComponents container, PipelineSettings pipelineSettings) in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 194
   at NServiceBus.Features.FeatureActivator.SetupFeatures(IConfigureComponents container, PipelineSettings pipelineSettings) in C:\Build\src\NServiceBus.Core\Features\FeatureActivator.cs:line 59
   at NServiceBus.InitializableEndpoint.Initialize() in C:\Build\src\NServiceBus.Core\InitializableEndpoint.cs:line 48
   at NServiceBus.Endpoint.Create(EndpointConfiguration configuration) in C:\Build\src\NServiceBus.Core\Endpoint.cs:line 17
   at NServiceBus.Endpoint.<Start>d__1.MoveNext() in C:\Build\src\NServiceBus.Core\Endpoint.cs:line 0
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNo```

**Comment by mikeminutillo** [comment]
Reproduced locally. The available version of the plugin was incompatible with Beta4. A new version has been released which is compatible with Beta4.

This is on NuGet as [ServiceControl.Plugin.Nsb6.CustomChecks 1.0.0.Beta4](https://www.nuget.org/packages/ServiceControl.Plugin.Nsb6.CustomChecks/1.0.0-beta0004)
